services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: "inventory-manager"
    networks:
      - network
    env_file:
      - .env
  authorization-server:
    build: ./authorization-server
    ports:
      - "9000:9000"
    networks:
      - network
    env_file:
      - .env
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    networks:
      - network
  users-service:
    build: ./users-service
    ports:
      - "8081:8081"
    networks:
      - network
    env_file:
      - .env
  products-service:
    build: ./products-service
    ports:
      - "8082:8082"
    networks:
      - network
    env_file:
      - .env

networks:
  network:
    driver: bridge